### ISSUE TITLE
An error occurred when clicking on a wallet

### ISSUE THREAD

**Issue by AnhTu6610** [WalletConnect/WalletConnectModalFlutter#1]
```
[###] |-->  Null check operator used on a null value
[###] |-->  #0      _WalletConnectModalState._onWalletDataSelected
walletconnect_modal.dart:344
#1      GridList._buildGridList.<anonymous closure>.<anonymous closure>.<anonymous closure>
grid_list.dart:121
#2      _InkResponseState.handleTap
ink_well.dart:1154
#3      GestureRecognizer.invokeCallback
recognizer.dart:275
#4      TapGestureRecognizer.handleTapUp
tap.dart:654
#5      BaseTapGestureRecognizer._checkUp
tap.dart:311
#6      BaseTapGestureRecognizer.acceptGesture
tap.dart:281
#7      GestureArenaManager.sweep
arena.dart:167
#8      GestureBinding.handleEvent
binding.dart:469
#9      GestureBinding.dispatchEvent
binding.dart:445
#10     RendererBinding.dispatchEvent
binding.dart:331
#11     GestureBinding._handlePointerEventImmediately
binding.dart:400
#12     GestureBinding.handlePointerEvent
binding.dart:363
#13     GestureBinding._flushPointerEventQueue
binding.dart:320
#14     GestureBinding._handlePointerDataPacket
binding.dart:293
#15     _rootRunUnary (dart:async/zone.dart:1415:13)
#16     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#18     _invoke1 (dart:ui/hooks.dart:160:10)
#19     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
```

**Comment by Luzzotica** [comment]
Multiple updates have been made to the library in the past two weeks.

I am not sure if this issue have been resolved, but I have personally not run into it.

I will close this issue, if it happens to you again, reopen it.

**Comment by Rmzn7** [comment]
25 of July, encountered this issue. Using walletconnect_modal_flutter: ^1.1.2
My assumption is that if a wallet was connected before, the issue occurs. After ending the session in MetaMask, started working pretty fine.
